# Generated by Django 3.2 on 2021-04-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
