# Generated by Django 3.2 on 2021-04-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
