# Generated by Django 3.2 on 2021-04-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0009_rename_relationshipmanager_relationshipmgr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationshipMgr',
            new_name='RelationshipManager',
        ),
    ]
