# Generated by Django 3.2 on 2021-05-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilesApp', '0010_rename_relationshipmgr_relationshipmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationshipManager',
        ),
    ]
